/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jlayer.app;

/**
 *
 * @author gko
 */
@SuppressWarnings("serial")
public class MandelbrotFrame extends javax.swing.JFrame {

    /**
     * Creates new form MandelbrotFrame
     */
    public MandelbrotFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mandelbrotActions = new MandelbrotActions(this);
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton(mandelbrotActions.initAction);
        jButton2 = new javax.swing.JButton(mandelbrotActions.loopAction);
        jButton3 = new javax.swing.JButton(mandelbrotActions.parallelAction);
        mandelbrotStatusBar = new org.jlayer.app.MandelbrotStatusBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        mandelbrotPanel = new MandelbrotPanel(mandelbrotActions.mandelbrotNet);
        myBlinker = new javax.swing.JLabel();
        myBlinker.setVisible(false);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem(mandelbrotActions.initAction);
        jMenuItem2 = new javax.swing.JMenuItem(mandelbrotActions.loopAction);
        jMenuItem3 = new javax.swing.JMenuItem(mandelbrotActions.parallelAction);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JLayer - Computing a Graphiical Represesntation of the Mandelbrot Set");
        setPreferredSize(new java.awt.Dimension(1400, 1050));

        jToolBar1.setRollover(true);

        jButton1.setText("Init");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.setText("");
        jToolBar1.add(jButton1);

        jButton2.setText("Loop");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.setText("");
        jToolBar1.add(jButton2);

        jButton3.setText("Parallel");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.setText("");
        jToolBar1.add(jButton3);

        mandelbrotStatusBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mandelbrotStatusBarLayout = new javax.swing.GroupLayout(mandelbrotStatusBar);
        mandelbrotStatusBar.setLayout(mandelbrotStatusBarLayout);
        mandelbrotStatusBarLayout.setHorizontalGroup(
            mandelbrotStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mandelbrotStatusBarLayout.setVerticalGroup(
            mandelbrotStatusBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        myBlinker.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        myBlinker.setForeground(new java.awt.Color(255, 51, 51));
        myBlinker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myBlinker.setText("IMAGE UNDER CONSTRUCTION");

        javax.swing.GroupLayout mandelbrotPanelLayout = new javax.swing.GroupLayout(mandelbrotPanel);
        mandelbrotPanel.setLayout(mandelbrotPanelLayout);
        mandelbrotPanelLayout.setHorizontalGroup(
            mandelbrotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mandelbrotPanelLayout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(myBlinker, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(641, Short.MAX_VALUE))
        );
        mandelbrotPanelLayout.setVerticalGroup(
            mandelbrotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mandelbrotPanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(myBlinker, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(mandelbrotPanel);

        jMenu1.setText("Network");

        jMenuItem1.setText("Init");
        jMenuItem1.setIcon(null);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(null);
        jMenuItem2.setText("Loop");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Parallel");
        jMenuItem3.setIcon(null);
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mandelbrotStatusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mandelbrotStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MandelbrotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MandelbrotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MandelbrotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MandelbrotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MandelbrotFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    javax.swing.JPanel mandelbrotPanel;
    org.jlayer.app.MandelbrotStatusBar mandelbrotStatusBar;
    javax.swing.JLabel myBlinker;
    // End of variables declaration//GEN-END:variables

    // my variable declarations
    MandelbrotActions mandelbrotActions;
}
